services:
  kibana:
    networks:
      home:
    ports:
      - "5601:5601"
    image: kibana:8.16.1  

  elasticsearch:
    image: elasticsearch:8.16.1
    networks:
      home:
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type-single-node"
networks:
  home:  